language: python
python:
  - "3.9"

branches:
  only:
    - master

deploy:
  provider: heroku
  app: chuvsu-forum
  api_key:
    secure: "d8bb47c8-aeb7-4db6-944a-ddb17d857e9a"

script:
  - echo "test debila"

notifications:
  email:
    recipients:
      - muzykantov99@gmail.com
    on_success: never
    on_failure: always