language: python
python:
  - "3.9"

sudo: false

branches:
  only:
    - master

script:
  - pytest

notifications:
  email:
    recipients:
      - muzykantov99@gmail.com
    on_success: never
    on_failure: always